language: julia
os:
  - linux
  - osx
julia:
  - 1.1
  - nightly
matrix:
  allow_failures:
    julia: nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'using Pkg; pkg"build QuantumWalk";'
  - julia --code-coverage test/runtests.jl 
after_success:
  - julia --depwarn=no -e 'using Pkg; cd(Pkg.dir("QuantumWalk")); Pkg.add("Coverage");'
  - julia --depwarn=no -e 'using Coverage; Coveralls.submit(process_folder())'
  - julia -e 'using Pkg; Pkg.add("Documenter"); cd(Pkg.dir("QuantumWalk")); include(joinpath("docs", "make.jl"))'

