language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'using Pkg; Pkg.add("Expokit")'
  - julia -e 'using Pkg; Pkg.add("LightGraphs")'
  - julia -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("QuantumWalk")'
  - julia -e 'using Pkg; Pkg.test("QuantumWalk"; coverage=true)'
after_success:
  - julia --depwarn=no -e 'using Pkg; cd(Pkg.dir("QuantumWalk")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
  - julia -e 'using Pkg; Pkg.add("Documenter"); cd(Pkg.dir("QuantumWalk")); include(joinpath("docs", "make.jl"))'
